<?php namespace App\Haramain\SistemKeuangan\SubKasir;

use App\Haramain\SistemKeuangan\SubNeraca\SaldoHutangPembelianRepo;
use App\Models\Purchase\Pembelian;

class HutangPembelianFromPembelian extends HutangPembelianRepo
{
    public function __construct(Pembelian $pembelian)
    {
        $this->saldoHutangPembelianId = $pembelian->supplier_id;
        $this->hutangableType = $pembelian::class;
        $this->hutangableId = $pembelian->id;
        $this->statusBayar = $pembelian->status_bayar;
        $this->kurangBayar = $pembelian->total_bayar;
    }

    public function store()
    {
        SaldoHutangPembelianRepo::build($this->saldoHutangPembelianId, $this->kurangBayar)->pembelian();
        return parent::store(); // TODO: Change the autogenerated stub
    }

    public function update()
    {
        SaldoHutangPembelianRepo::build($this->saldoHutangPembelianId, $this->kurangBayar)->retur();
        return parent::update(); // TODO: Change the autogenerated stub
    }

    public function rollback()
    {
        SaldoHutangPembelianRepo::build($this->saldoHutangPembelianId, $this->kurangBayar)->penjualanRollback();
        return $this->getDataById();
    }

    public function destroy()
    {
        SaldoHutangPembelianRepo::build($this->saldoHutangPembelianId, $this->kurangBayar)->penjualanRollback();
        return $this->getDataById()->delete();
    }
}
