<?php namespace App\Haramain\SistemKeuangan\SubKasir;

use App\Haramain\SistemKeuangan\SubNeraca\SaldoPiutangPenjualanRepo;
use App\Models\Penjualan\PenjualanRetur;

class PiutangPenjualanFromRetur extends PiutangPenjualanRepo
{
    public function __construct(PenjualanRetur $penjualanRetur)
    {
        $this->saldoPiutangPenjualanId = $penjualanRetur->customer_id;
        $this->jurnalSetPiutangAwalId = null;
        $this->piutangableType = $penjualanRetur::class;
        $this->piutangableId = $penjualanRetur->id;
        $this->statusBayar = $penjualanRetur->status_bayar;
        $this->kurangBayar = 0 - $penjualanRetur->total_bayar;
    }

    public static function build(PenjualanRetur $penjualanRetur)
    {
        return new static($penjualanRetur);
    }

    public function store()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->retur();
        return parent::store(); // TODO: Change the autogenerated stub
    }

    public function update()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->retur();
        return parent::update(); // TODO: Change the autogenerated stub
    }

    /** @noinspection PhpMemberCanBePulledUpInspection */
    public function rollback()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->returRollback();
        return $this->getDataById();
    }

    /** @noinspection PhpMemberCanBePulledUpInspection */
    public function destroy()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->returRollback();
        return $this->getDataById()->delete();
    }
}
