<?php namespace App\Haramain\SistemKeuangan\SubKasir;

use App\Haramain\SistemKeuangan\SubNeraca\SaldoPiutangPenjualanRepo;
use App\Models\Penjualan\Penjualan;

class PiutangPenjualanFromPenjualan extends PiutangPenjualanRepo
{
    public function __construct(Penjualan $penjualan)
    {
        $this->saldoPiutangPenjualanId = $penjualan->customer_id;
        $this->jurnalSetPiutangAwalId = null;
        $this->piutangableType = $penjualan::class;
        $this->piutangableId = $penjualan->id;
        $this->statusBayar = $penjualan->status_bayar;
        $this->kurangBayar = $penjualan->total_bayar;
    }

    public static function build(Penjualan $penjualan)
    {
        return new static($penjualan);
    }

    public function store()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->penjualan();
        return parent::store(); // TODO: Change the autogenerated stub
    }

    public function update()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->penjualan();
        return parent::update(); // TODO: Change the autogenerated stub
    }

    /** @noinspection PhpMemberCanBePulledUpInspection */
    public function rollback()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->penjualanRollback();
        return $this->getDataById();
    }

    /** @noinspection PhpMemberCanBePulledUpInspection */
    public function destroy()
    {
        SaldoPiutangPenjualanRepo::build($this->saldoPiutangPenjualanId, $this->kurangBayar)->penjualanRollback();
        return $this->getDataById()->delete();
    }
}
