<x-atoms.table.td>
    {{$row->kode}}
</x-atoms.table.td>
<x-atoms.table.td>
    {{$row->tgl_penerimaan}}
</x-atoms.table.td>
<x-atoms.table.td>
    {{$row->customer->nama}}
</x-atoms.table.td>
<x-atoms.table.td>
    {{$row->nominal_kas}}
</x-atoms.table.td>
<x-atoms.table.td>
    {{--button--}}
</x-atoms.table.td>
